spring.datasource.url=jdbc:postgresql://localhost:5432/data_portfolio
spring.datasource.username=portfolio_admin
spring.datasource.password=portfolio123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações de e-mail (substitua com suas credenciais)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smurfbomfim@gmail.com
spring.mail.password=pesy wrtb qftv ifki
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true